version: "3"
services:
  server:
    build: "."
    image: "server"
    ports:
      - "${HOST_PORT}:${HOST_PORT}"
    depends_on:
      - "db"
    links:
      - "db:${DB_HOST}"
  db:
    restart: "on-failure"
    image: "redis"
    expose:
      - ${DB_PORT}
