// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/add-question.ts";
import * as $1 from "./routes/api/delete-question.ts";
import * as $2 from "./routes/api/list-questions.ts";
import * as $3 from "./routes/api/pick-question.ts";
import * as $4 from "./routes/api/send-answer.ts";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/question-list.tsx";

const manifest = {
  routes: {
    "./routes/api/add-question.ts": $0,
    "./routes/api/delete-question.ts": $1,
    "./routes/api/list-questions.ts": $2,
    "./routes/api/pick-question.ts": $3,
    "./routes/api/send-answer.ts": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/question-list.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
